### ISSUE TITLE
How to change saturation, contrast and brightness ?

### ISSUE THREAD

**Issue by Pan-Chenliang** [rt-net/jetson_nano_cuda_csi_cam_ros#8]
I used your project https://github.com/rt-net/jetson_nano_csi_cam_ros before and can change image brightness by adding `videobalance` to gscam config. But that project gives a low framerate so I tried this one.
It satisfied my needs of high fps, but I have no idea where to change saturation, contrast or brightness. Is there any method to achieve this or could you add some new params to adjust output image ?
Thanks very much.

**Comment by Tiryoh** [comment]
Hi @Pan-Chenliang,

This ROS package uses [jetson-utils](https://github.com/dusty-nv/jetson-utils) to access the camera.
Jetson-utils seems to have settings to change contrast and brightness.
https://github.com/dusty-nv/jetson-utils/issues/68

You may be able to reflect it by adding a parameter to video_options.
https://github.com/rt-net/jetson_nano_cuda_csi_cam_ros/blob/cd516d470fed232d1313367b3bd8aa9ce6408d9f/src/video_stream_node.cpp#L86

At this time, there are no plans to change the parameters of this package, test it, and release it.

**Comment by Pan-Chenliang** [comment]
Great ! Thank you @Tiryoh
